global:
  name: train-CAAC
  phase: train
  workdir: workdir_SLPR
  seed: 42
  contrastive: True
  projection_type: 'projection_free'
  supervised: True
  temperature: 0.15


dataset:
  linguistic: 'Chinese'
  charset_path: data/alphabet_ch_6067.txt

  train: {
    roots: ['data/training/SLPR'],
    batch_size: 128
  }

  test: {
   roots: ['data/testing/SLPR'],
   batch_size: 128
  }

  imgH: 32
  imgW: 256
  max_length: 25
  data_aug: True
  multiscales: True
  case_sensitive: False
  eval_case_sensitive: False
  smooth_label: False
  smooth_factor: 0.1
  one_hot_y: False

  data_loader: {
    num_workers: 6,
    pin_memory: True,
  }

training:
  epochs: 200
  pct_start: 0.1
  show_iters: 40
  eval_iters: 40
  start_eval_iters: 2000
  save_iters: 4000
  start_iters: 0
  stats_iters: 1000000

optimizer:
  type: AdamW
  clip_grad: 20
  lr: 0.005
  wd: 0.1
  args: {
    betas: !!python/tuple [0.9, 0.999],
  }
  loss_weight: {
    sup_con: 1.0,
    ce: 2.0,
  }

model:
  name: "Modules.model.Model"
  checkpoint: ~
  backbone: 'resnet45'
  d_model: 512
