global:
  name: train-CAAC
  phase: train
  workdir: workdir_Chinese
  seed: 42
  contrastive: True
  projection_type: 'projection_free'    # wordArt   projection_free    SimCLR   BiLSTM
  supervised: True
  temperature: 0.15


dataset:
  charset_path: data/benchmark_ch_7934.txt

  train: {
    roots: ['data/training/Scene'],
    batch_size: 384
  }
  
  # /path/to/evaluation dataset for phase: train
  # /path/to/test dataset for phase: test, set the batch_size 1
  test: {
    roots: ['data/evaluating/Scene'],
    batch_size: 384
  }
  image_only: True

  imgH: 32
  imgW: 256
  max_length: 40
  data_aug: True
  multiscales: False
  case_sensitive: False
  eval_case_sensitive: False
  smooth_label: False
  smooth_factor: 0.1
  one_hot_y: False

  data_loader: {
    num_workers: 16,
    pin_memory: True,
  }

training:
  epochs: 120
  pct_start: 0.025
  show_iters: 1325
  eval_iters: 1325
  start_eval_iters: 10000
  save_iters: 40000
  start_iters: 0
  stats_iters: 1000000

optimizer:
  type: AdamW
  clip_grad: 20
  lr: 0.0008
  wd: 0.01
  args: {
    betas: !!python/tuple [0.9, 0.999],
  }
  loss_weight: {
    sup_con: 1.0,
    ce: 2.0,
  }

model:
  name: "Modules.model.Model"
  checkpoint: ''
  backbone: 'swin'
  strict: True
  d_model: 512
